"""4to intento

Revision ID: 3b07e3e61bfe
Revises: 
Create Date: 2023-12-04 22:35:56.855699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b07e3e61bfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.Column('administrador', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('imagenes_usuario',
    sa.Column('id_imagen', sa.Integer(), nullable=False),
    sa.Column('datos', sa.LargeBinary(), nullable=False),
    sa.Column('renderizado_datos', sa.Text(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    op.create_table('receta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('dificultad', sa.String(length=100), nullable=False),
    sa.Column('tiempo_preparacion', sa.String(length=100), nullable=False),
    sa.Column('ingredientes', sa.Text(), nullable=False),
    sa.Column('instrucciones', sa.Text(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receta_id'], ['receta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagenes_receta',
    sa.Column('id_imagen', sa.Integer(), nullable=False),
    sa.Column('datos', sa.LargeBinary(), nullable=False),
    sa.Column('datos_renderizados', sa.Text(), nullable=False),
    sa.Column('id_receta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_receta'], ['receta.id'], ),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagenes_receta')
    op.drop_table('favorito')
    op.drop_table('receta')
    op.drop_table('imagenes_usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
